app/uk/gov/hmrc/emcstfe/config/EnrolmentKeys.scala, app/uk/gov/hmrc/emcstfe/connectors/BaseConnector.scala, app/uk/gov/hmrc/emcstfe/connectors/ChrisConnector.scala, app/uk/gov/hmrc/emcstfe/connectors/httpParsers/ChrisXMLHttpParser.scala, app/uk/gov/hmrc/emcstfe/controllers/GetMovementController.scala, app/uk/gov/hmrc/emcstfe/controllers/GetMovementListController.scala, app/uk/gov/hmrc/emcstfe/controllers/predicates/AuthAction.scala, app/uk/gov/hmrc/emcstfe/models/auth/UserRequest.scala, app/uk/gov/hmrc/emcstfe/utils/Logging.scala, app/uk/gov/hmrc/emcstfe/utils/SoapUtils.scala, conf/application.conf, conf/logback-test.xml, conf/logback.xml, it/uk/gov/hmrc/emcstfe/GetMovementIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/GetMovementListIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/stubs/AuthStub.scala, it/uk/gov/hmrc/emcstfe/stubs/DownstreamStub.scala, it/uk/gov/hmrc/emcstfe/support/IntegrationBaseSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/GetMovementControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/GetMovementListControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/predicates/AuthActionSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/predicates/FakeAuthAction.scala, test/uk/gov/hmrc/emcstfe/fixtures/BaseFixtures.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementFixture.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementListFixture.scala, test/uk/gov/hmrc/emcstfe/utils/LoggingSpec.scala
**Notes**:
- AuthAction added to be used as the action within controllers, guarding endpoints against unauthorised requests
- Logging util updated to simplify the consistency of logging across services
- ⚠️ Journey Tests and Performance Tests will need to be updated prior to this PR being merged.
=> [ETFE-438] Added AuthAction and updated controller action to guard them

app/uk/gov/hmrc/emcstfe/connectors/httpParsers/ChrisXMLHttpParser.scala, app/uk/gov/hmrc/emcstfe/models/response/ErrorResponse.scala, app/uk/gov/hmrc/emcstfe/utils/HMRCMarkUtil.scala, app/uk/gov/hmrc/emcstfe/utils/SoapUtils.scala, conf/application.conf, conf/logback-test.xml, test/uk/gov/hmrc/emcstfe/connectors/ChrisConnectorSpec.scala, test/uk/gov/hmrc/emcstfe/connectors/httpParsers/ChrisXMLHttpParserSpec.scala, test/uk/gov/hmrc/emcstfe/mocks/utils/MockHMRCMarkUtil.scala, test/uk/gov/hmrc/emcstfe/mocks/utils/MockSoapUtils.scala, test/uk/gov/hmrc/emcstfe/utils/SoapUtilsSpec.scala
Dependent PRs
- #17
~I will rebase once the dependent PRs are merged~ rebased
=> [ETFE-516] add utility function to prepare XML for submission

app/uk/gov/hmrc/emcstfe/models/response/GetMovementResponse.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementFixture.scala, test/uk/gov/hmrc/emcstfe/models/response/GetMovementResponseSpec.scala
ChRIS Stub PR:
- https://github.com/hmrc/emcs-tfe-chris-stub/pull/13
=> [ETFE-623] Update to match the QA response

app/uk/gov/hmrc/emcstfe/config/AppConfig.scala, app/uk/gov/hmrc/emcstfe/models/mongo/ReportReceiptUserAnswers.scala, app/uk/gov/hmrc/emcstfe/repositories/ReportReceiptUserAnswersRepository.scala, app/uk/gov/hmrc/emcstfe/utils/TimeMachine.scala, conf/application.conf, it/uk/gov/hmrc/emcstfe/repositories/ReportReceiptUserAnswersRepositorySpec.scala, it/uk/gov/hmrc/emcstfe/support/IntegrationBaseSpec.scala, project/AppDependencies.scala, test/uk/gov/hmrc/emcstfe/config/AppConfigSpec.scala, test/uk/gov/hmrc/emcstfe/models/mongo/ReportReceiptUserAnswersSpec.scala, test/uk/gov/hmrc/emcstfe/utils/TimeMachineSpec.scala
App-Config PRs:
- Dev: https://github.com/hmrc/app-config-development/pull/7557
- QA: https://github.com/hmrc/app-config-qa/pull/17697
- Staging: https://github.com/hmrc/app-config-staging/pull/12303
=> [ETFE-685] Added ReportReceiptUserAnswers mongo collection (based on current FE UserAnswers)

app/uk/gov/hmrc/emcstfe/config/AppConfig.scala, app/uk/gov/hmrc/emcstfe/config/Module.scala, app/uk/gov/hmrc/emcstfe/connectors/userAllowList/UserAllowListConnector.scala, app/uk/gov/hmrc/emcstfe/connectors/userAllowList/UserAllowListHttpParser.scala, app/uk/gov/hmrc/emcstfe/controllers/GetMovementController.scala, app/uk/gov/hmrc/emcstfe/controllers/GetMovementListController.scala, app/uk/gov/hmrc/emcstfe/controllers/ReportReceiptUserAnswersController.scala, app/uk/gov/hmrc/emcstfe/controllers/SubmitReportOfReceiptController.scala, app/uk/gov/hmrc/emcstfe/controllers/actions/AuthAction.scala, app/uk/gov/hmrc/emcstfe/controllers/actions/AuthActionHelper.scala, app/uk/gov/hmrc/emcstfe/controllers/actions/UserAllowListAction.scala, app/uk/gov/hmrc/emcstfe/controllers/testOnly/SubmitDraftMovementController.scala, app/uk/gov/hmrc/emcstfe/models/request/CheckUserAllowListRequest.scala, app/uk/gov/hmrc/emcstfe/models/response/ErrorResponse.scala, conf/application.conf, it/uk/gov/hmrc/emcstfe/connectors/UserAllowListConnectorISpec.scala, test/uk/gov/hmrc/emcstfe/controllers/GetMovementControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/GetMovementListControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/ReportReceiptUserAnswersControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/SubmitReportOfReceiptControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/actions/AuthActionSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/actions/FakeAuthAction.scala, test/uk/gov/hmrc/emcstfe/controllers/actions/FakeUserAllowListAction.scala, test/uk/gov/hmrc/emcstfe/controllers/actions/UserAllowListActionSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/testOnly/SubmitDraftMovementControllerSpec.scala, test/uk/gov/hmrc/emcstfe/mocks/connectors/MockUserAllowListConnector.scala, test/uk/gov/hmrc/emcstfe/support/UnitSpec.scala
- https://github.com/hmrc/app-config-base/pull/8662
- https://github.com/hmrc/app-config-qa/pull/18646
- https://github.com/hmrc/app-config-production/pull/18320
=> [ETFE-966] implement user-allow-list functionality

app/uk/gov/hmrc/emcstfe/models/common/JourneyTime.scala, app/uk/gov/hmrc/emcstfe/models/createMovement/BodyEadEsadModel.scala, test/uk/gov/hmrc/emcstfe/fixtures/CreateMovementFixtures.scala, test/uk/gov/hmrc/emcstfe/models/common/JourneyTimeSpec.scala
Contract Tests PR:
- https://github.com/hmrc/emcs-tfe-contract-tests/pull/17
=> [ETFE-1571] Fix issues identified by contract tests

app/uk/gov/hmrc/emcstfe/models/mongo/GetMovementMongoResponse.scala, app/uk/gov/hmrc/emcstfe/repositories/GetMovementRepository.scala, app/uk/gov/hmrc/emcstfe/services/GetMovementService.scala, it/uk/gov/hmrc/emcstfe/controllers/GetMovementIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/repositories/GetMovementRepositorySpec.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementFixture.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementIfChangedFixture.scala, test/uk/gov/hmrc/emcstfe/mocks/repository/MockGetMovementRepository.scala, test/uk/gov/hmrc/emcstfe/mocks/services/MockGetMovementService.scala, test/uk/gov/hmrc/emcstfe/models/mongo/GetMovementMongoResponseSpec.scala, test/uk/gov/hmrc/emcstfe/services/GetMovementServiceSpec.scala
This App-Config-Production PR needs merging with this:
- https://github.com/hmrc/app-config-production/pull/19373
=> [ETFE-1638] Updated the GetMovement repo to be based on ARC only

README.md, app/uk/gov/hmrc/emcstfe/controllers/SubmitCreateMovementController.scala, app/uk/gov/hmrc/emcstfe/controllers/userAnswers/CreateMovementUserAnswersController.scala, app/uk/gov/hmrc/emcstfe/models/mongo/CreateMovementUserAnswers.scala, app/uk/gov/hmrc/emcstfe/repositories/CreateMovementUserAnswersRepository.scala, app/uk/gov/hmrc/emcstfe/services/userAnswers/CreateMovementUserAnswersService.scala, conf/app.routes, conf/application.conf, conf/userAnswers.routes, it/uk/gov/hmrc/emcstfe/controllers/CreateMovementUserAnswersIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/repositories/CreateMovementUserAnswersRepositorySpec.scala, project/plugins.sbt, test/uk/gov/hmrc/emcstfe/controllers/SubmitCreateMovementControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/userAnswers/CreateMovementUserAnswersControllerSpec.scala, test/uk/gov/hmrc/emcstfe/fixtures/BaseFixtures.scala, test/uk/gov/hmrc/emcstfe/models/mongo/CreateMovementUserAnswersSpec.scala, test/uk/gov/hmrc/emcstfe/services/userAnswers/CreateMovementUserAnswersServiceSpec.scala
needs to be merged in with https://github.com/hmrc/emcs-tfe-create-movement-frontend/pull/100
=> ETFE-2346 lrn becomes draftId

app/uk/gov/hmrc/emcstfe/connectors/BaseEisConnector.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMessageStatisticsFixtures.scala
Reverts hmrc/emcs-tfe#89
Asked not to make this change by EIS
=> Revert "[ETFE-remove-millies] remove millies from EIS headers"

conf/application.conf
Set to 2hours so that the draft doesn't time out every 15 minutes locally.
=> [ETFE-ChangeLocalTTLForCreateMovement] Up local TTL of create movement draft

app/uk/gov/hmrc/emcstfe/config/AppConfig.scala, app/uk/gov/hmrc/emcstfe/connectors/BaseEisConnector.scala, app/uk/gov/hmrc/emcstfe/connectors/EisConnector.scala, app/uk/gov/hmrc/emcstfe/models/request/eis/EisHeaders.scala, conf/application.conf, test/uk/gov/hmrc/emcstfe/connectors/EisConnectorSpec.scala, test/uk/gov/hmrc/emcstfe/mocks/connectors/MockHttpClient.scala
To be reviewed/merged with https://github.com/hmrc/emcs-tfe-stub/pull/23
=> [ETFE-2809] added EMCS08 bearer token

app/uk/gov/hmrc/emcstfe/models/createMovement/WineProductModel.scala, project/plugins.sbt, test/uk/gov/hmrc/emcstfe/fixtures/CreateMovementFixtures.scala
~Running JT's, PT's and contract tests locally~
Tested against local stub and works (doesn't work on main locally)
=> [ETFE-WineOperationCodeTweak] - Added WineOperationCode to WineOperation element

app/uk/gov/hmrc/emcstfe/featureswitch/core/config/FeatureSwitching.scala
Also requires https://github.com/hmrc/alert-config/pull/3263
=> SendToEIS feature toggle logger

app/uk/gov/hmrc/emcstfe/controllers/GetMovementHistoryEventsController.scala, app/uk/gov/hmrc/emcstfe/models/request/GetMovementHistoryEventsRequest.scala, app/uk/gov/hmrc/emcstfe/services/GetMovementHistoryEventsService.scala, it/uk/gov/hmrc/emcstfe/controllers/GetMovementHistoryEventsIntegrationSpec.scala, project/plugins.sbt, test/uk/gov/hmrc/emcstfe/controllers/GetMovementHistoryEventsControllerSpec.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementHistoryEventsFixture.scala, test/uk/gov/hmrc/emcstfe/mocks/services/MockGetMovementHistoryEventsService.scala, test/uk/gov/hmrc/emcstfe/models/request/GetMovementHistoryEventsRequestSpec.scala, test/uk/gov/hmrc/emcstfe/services/GetMovementHistoryEventsServiceSpec.scala
=> [ETFE-3269] - Added ChRIS integration for event history calls

app/uk/gov/hmrc/emcstfe/controllers/GetSubmissionFailureMessageController.scala, app/uk/gov/hmrc/emcstfe/models/response/getSubmissionFailureMessage/GetSubmissionFailureMessageResponse.scala, app/uk/gov/hmrc/emcstfe/repositories/CreateMovementUserAnswersRepository.scala, it/uk/gov/hmrc/emcstfe/controllers/GetSubmissionFailureMessageIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/repositories/CreateMovementUserAnswersRepositorySpec.scala, test/uk/gov/hmrc/emcstfe/controllers/GetSubmissionFailureMessageControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/testOnly/InsertCreateMovementUserAnswersControllerSpec.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetSubmissionFailureMessageFixtures.scala, test/uk/gov/hmrc/emcstfe/models/response/getSubmissionFailureMessage/GetSubmissionFailureMessageResponseSpec.scala
Note, can't be merged until FE PR is ready. Then can be merged together.
=> [ETFE-3569] Rename isTFESubmission to draftMovementExists

app/uk/gov/hmrc/emcstfe/controllers/GetMovementController.scala, app/uk/gov/hmrc/emcstfe/models/mongo/GetMovementMongoResponse.scala, app/uk/gov/hmrc/emcstfe/models/request/GetMovementRequest.scala, app/uk/gov/hmrc/emcstfe/services/GetMovementService.scala, conf/app.routes, it/uk/gov/hmrc/emcstfe/controllers/GetMovementIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/controllers/LegacyMessagesControllerIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/repositories/GetMovementRepositorySpec.scala, test/uk/gov/hmrc/emcstfe/connectors/ChrisConnectorSpec.scala, test/uk/gov/hmrc/emcstfe/connectors/EisConnectorSpec.scala, test/uk/gov/hmrc/emcstfe/connectors/httpParsers/ChrisXMLHttpParserSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/GetMovementControllerSpec.scala, test/uk/gov/hmrc/emcstfe/controllers/LegacyMessagesControllerSpec.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementFixture.scala, test/uk/gov/hmrc/emcstfe/fixtures/GetMovementIfChangedFixture.scala, test/uk/gov/hmrc/emcstfe/mocks/services/MockGetMovementService.scala, test/uk/gov/hmrc/emcstfe/models/mongo/GetMovementMongoResponseSpec.scala, test/uk/gov/hmrc/emcstfe/models/response/GetMovementIfChangedResponseSpec.scala, test/uk/gov/hmrc/emcstfe/models/response/getMovement/GetMovementResponseSpec.scala, test/uk/gov/hmrc/emcstfe/models/response/getMovement/MovementViewHistoryAndExtraDataModelSpec.scala, test/uk/gov/hmrc/emcstfe/services/GetMovementServiceSpec.scala, test/uk/gov/hmrc/emcstfe/services/LegacyMessagesServiceSpec.scala, test/uk/gov/hmrc/emcstfe/utils/XmlUtilsSpec.scala
**Note**:
- Requires Stub change: https://github.com/hmrc/emcs-tfe-stub/pull/92
=> [ETFE-3577] sequenceNumber passed through as optional queryString and not sent to EIS when latest is requested

test/uk/gov/hmrc/emcstfe/fixtures/CreateMovementSearchFixture.scala
To prevent the occasional faillure caused by Mongo TTL kicking in.
=> [ETFE-TestFixture-DateInFuture] Ensure lastUpdated isn't in the past

app/uk/gov/hmrc/emcstfe/services/userAllowList/UserAllowListService.scala, conf/application.conf, it/uk/gov/hmrc/emcstfe/controllers/userAllowList/UserAllowListControllerIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/support/IntegrationBaseSpec.scala, test/uk/gov/hmrc/emcstfe/connectors/UserAllowListConnectorSpec.scala, test/uk/gov/hmrc/emcstfe/services/userAllowList/UserAllowListServiceSpec.scala
Small bug fix, plus add missing app-conf values
=> [ETFE-4093] Add extra service config to match the Public Beta traffic thresholds

app/uk/gov/hmrc/emcstfe/featureswitch/core/config/FeatureSwitchingModule.scala, app/uk/gov/hmrc/emcstfe/services/userAllowList/UserAllowListService.scala, it/uk/gov/hmrc/emcstfe/controllers/userAllowList/UserAllowListControllerIntegrationSpec.scala, test/uk/gov/hmrc/emcstfe/services/userAllowList/UserAllowListServiceSpec.scala
Small fix, so that if Private Beta and Public Throttling are both disabled, then global access to the service is alllowed.
=> [ETFE-4423] Small bug fix, for UserAllowService

app/uk/gov/hmrc/emcstfe/config/AppConfig.scala, app/uk/gov/hmrc/emcstfe/controllers/templates/MovementTemplatesController.scala, app/uk/gov/hmrc/emcstfe/models/mongo/CreateMovementUserAnswers.scala, app/uk/gov/hmrc/emcstfe/models/mongo/MovementTemplate.scala, app/uk/gov/hmrc/emcstfe/models/response/ErrorResponse.scala, app/uk/gov/hmrc/emcstfe/repositories/CreateMovementUserAnswersRepository.scala, app/uk/gov/hmrc/emcstfe/repositories/MovementTemplatesRepository.scala, app/uk/gov/hmrc/emcstfe/services/templates/MovementTemplatesService.scala, app/uk/gov/hmrc/emcstfe/testOnly/controllers/InsertMovementTemplateController.scala, conf/app.routes, conf/application.conf, conf/templates.routes, conf/test.routes, it/uk/gov/hmrc/emcstfe/controllers/MovementTemplatesIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/controllers/testOnly/InsertMovementTemplateIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/repositories/MovementTemplatesRepositorySpec.scala, test/uk/gov/hmrc/emcstfe/controllers/templates/MovementTemplatesControllerSpec.scala, test/uk/gov/hmrc/emcstfe/fixtures/BaseFixtures.scala, test/uk/gov/hmrc/emcstfe/mocks/repository/MockMovementTemplatesRepository.scala, test/uk/gov/hmrc/emcstfe/mocks/services/MockMovementTemplatesService.scala, test/uk/gov/hmrc/emcstfe/mocks/utils/MockUUIDGenerator.scala, test/uk/gov/hmrc/emcstfe/services/templates/MovementTemplatesServiceSpec.scala
App Config PR:
- https://github.com/hmrc/app-config-base/pull/10961
=> [ETFE-4501] Added Templates APIs, Services and Mongo Collection

app/uk/gov/hmrc/emcstfe/controllers/templates/MovementTemplatesController.scala, app/uk/gov/hmrc/emcstfe/repositories/MovementTemplatesRepository.scala, app/uk/gov/hmrc/emcstfe/services/templates/MovementTemplatesService.scala, conf/templates.routes, it/uk/gov/hmrc/emcstfe/controllers/MovementTemplatesIntegrationSpec.scala, it/uk/gov/hmrc/emcstfe/repositories/MovementTemplatesRepositorySpec.scala, test/uk/gov/hmrc/emcstfe/controllers/templates/MovementTemplatesControllerSpec.scala, test/uk/gov/hmrc/emcstfe/mocks/repository/MockMovementTemplatesRepository.scala, test/uk/gov/hmrc/emcstfe/mocks/services/MockMovementTemplatesService.scala, test/uk/gov/hmrc/emcstfe/services/templates/MovementTemplatesServiceSpec.scala
Required so that CaM can retrieve all templates
=> [ETFE-4568] Make pagination for getList of templates optional
